### ISSUE TITLE
Reporte Practica DLL

### ISSUE THREAD

**Issue by Lissete7** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Lissete7#2]
[Reporte  DLL_Lizzete Léon González.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Lissete7/files/6359581/Reporte.DLL_Lizzete.Leon.Gonzalez.pdf)

**Comment by Sandra631** [comment]
[Uploading 2.- Rúbrica reporte de practica (2).pdf…]()

**Comment by Sandra631** [comment]
100%

**Comment by josealfredo79** [comment]
La calificación máxima es de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
